version: '3'
services:
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    image: surreal29/network-webapp-client
    environment:
      - CHOKIDAR_USEPOLLING=true
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    image: surreal29/network-webapp-api
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./backend/.env
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '80:80'
      - '443:443'
    image: surreal29/network-webapp-nginx
