version: '3'
services:
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    image: client
    environment:
      - CHOKIDAR_USEPOLLING=true
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    image: api
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./backend/.env
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    image: nginx
