version: '3'
services:
  frontend_dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    image: frontend_dev
    volumes:
      - /app/node_modules
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
  backend_dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - '5000:5000'
    image: backend_dev
    volumes:
      - ./backend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./backend/.env
